### PR TITLE
datamodel: include "_bucket"

### LINKED ISSUE #176: Ensure _bucket is preserved on updates
Create a record and see that internally the record has a ``_bucket``.
```
curl -k --header "Content-Type: application/json" \
--request POST \
--data '{"title":"Some title", "contributors": [{"name": "Doe, John"}]}' \
https://127.0.0.1:5000/api/records/?prettyprint=1
```

Make an update of the record and see that internally the record has now removed  ``_bucket``.

```
curl -k --header "Content-Type: application/json" --request PUT --data '{"title":"Some title", "contributors": [{"name": "Doe, John"}]}' https://127.0.0.1:5000/api/records/1?prettyprint=1
```
part of #177

### PR DESCRIPTION
**Pull request by slint**
closes #176

### CODE REVIEW

**Comment by slint** [comment]
Depends on https://github.com/inveniosoftware/invenio-records-rest/commit/b8db18e3c0a0943d99050c224ed858888d8a7595 and `invenio-records-rest v1.5.0`

**Comment by roksys** [comment]
LGTM. https://github.com/inveniosoftware/invenio needs `invenio-records-rest` pinned to at least 1.6.2 for this to work.

```
pccda22:invenio-records-rest rokas$ curl -k --header "Content-Type: application/json" --request POST --data '{"title":"Some title", "contributors": [{"name": "Doe, John"}]}' https://127.0.0.1:5000/api/records/?prettyprint=1
{
  "_bucket": "8e98e7dc-d0d7-482f-b42c-054be5df52fe", 
  "created": "2019-11-11T14:04:26.666522+00:00", 
  "id": "2", 
  "links": {
    "self": "https://127.0.0.1:5000/api/records/2"
  }, 
  "metadata": {
    "contributors": [
      {
        "name": "Doe, John"
      }
    ], 
    "id": "2", 
    "title": "Some title"
  }, 
  "revision": 0, 
  "updated": "2019-11-11T14:04:26.666529+00:00"
}
```

```
pccda22:invenio-records-rest rokas$ curl -k --header "Content-Type: application/json" --request PUT --data '{"title":"Some title updated", "contributors": [{"name": "Doe, John"}]}' https://127.0.0.1:5000/api/records/1?prettyprint=1
{
  "_bucket": "2cb5999a-ca16-4b45-adbf-9bec15fe3d76", 
  "created": "2019-11-11T14:04:19.621635+00:00", 
  "id": "1", 
  "links": {
    "self": "https://127.0.0.1:5000/api/records/1"
  }, 
  "metadata": {
    "contributors": [
      {
        "name": "Doe, John"
      }
    ], 
    "id": "1", 
    "title": "Some title updated"
  }, 
  "revision": 3, 
  "updated": "2019-11-11T14:06:09.796809+00:00"
}
```

**Comment by roksys** [comment]
Depends on - https://github.com/inveniosoftware/invenio/pull/3969

**Comment by frankois** [comment]
Tested and worked

**Pull request merged**
