### PR TITLE
scripts: allows installation of prereleases

### PR DESCRIPTION
**Pull request by Glignos**
Closes https://github.com/inveniosoftware/invenio/issues/4055

### CODE REVIEW

**Comment by ppanero** [comment]
I wonder if we should "just" wait:
- For the `--pre` because then we have to revert it. See https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/233
- For the folders invenio-assets might fix it. See https://github.com/inveniosoftware/invenio-assets/pull/134

WDYT?

**Comment by lnielsen** [comment]
What other pre-releases beside the pytest-celery are we getting when we specify the ``--pre`` tag? The tag is causing further troubles in InvenioRDM.

**Comment by ppanero** [comment]
@lnielsen This is what I got in my last InvenioRDM instance:
```
(alias_rdm) ~/Workspace/inveniosw/test/alias-rdm pip freeze | grep invenio
invenio==3.4.0a8
invenio-access==1.4.1
invenio-accounts==1.4.0a8
invenio-admin==1.2.1
invenio-app==1.3.0
invenio-app-rdm==0.17.4
invenio-assets==1.2.5
invenio-base==1.2.3
invenio-cache==1.1.0
invenio-celery==1.2.1
invenio-cli==0.19.4
invenio-communities==2.1.1
invenio-config==1.0.3
invenio-db==1.0.8
invenio-drafts-resources==0.6.2
invenio-files-rest==1.2.0
invenio-formatter==1.1.0a1
invenio-i18n==1.3.0a1
invenio-iiif==1.1.0
invenio-indexer==1.2.0
invenio-jsonschemas==1.1.0
invenio-logging==1.3.0
invenio-mail==1.0.2
invenio-oaiserver==1.2.0
invenio-oauth2server==1.3.0a2
invenio-oauthclient==1.4.0a1
invenio-pidrelations==1.0.0a7
invenio-pidstore==1.2.1
invenio-previewer==1.3.0a3
invenio-rdm-records==0.24.6
invenio-records==1.4.0a4
invenio-records-files==1.2.1
invenio-records-permissions==0.10.0
invenio-records-resources==0.8.7
invenio-records-rest==1.7.2
invenio-records-ui==1.2.0a1
invenio-rest==1.2.2
invenio-search==1.4.1
invenio-search-ui==2.0.0a9
-e git+https://github.com/ppanero/invenio-theme.git@e182e8d79be87c09ae9355de99566a8d971d235b#egg=invenio_theme
invenio-userprofiles==1.2.0a4
```

From what I can see, there are plans to get out of alpha every module **except PIDRELATIONS**. In addition, pytest-celery only  is needed if we are on "testing" phase in which case I think is "ok" to use `--pre`, the important part is that external users do not need it.

**Comment by lnielsen** [comment]
After discussion with @ppanero, we'll try to remove pytest-celery from Invenio-Celery and Pytest-Invenio, and release Invenio-PIDRelations in 0.x.0 release, so that we can get rid of the --pre flag.

I'm assigning to @ppanero to test the pytest-celery removal

**Comment by ppanero** [comment]
@lnielsen release PR for pidreleations. Contains migration to GH actions so It releases "fast". Note that is not the newest way of running tests, but GH actions team told me the newest changes will be applied when ready.

**Comment by ppanero** [comment]
@lnielsen invenio-celery PR https://github.com/inveniosoftware/invenio-celery/pull/73. How to deal with pytest-invenio, needs IRL discussion.

**Comment by ppanero** [comment]
@lnielsen demo of what happens with pytest-invenio when registering through plugins endpoint https://github.com/inveniosoftware/pytest-invenio/pull/61

**Comment by lnielsen** [comment]
Superseded.

**Pull request closed without merging**
